# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d0bf3428392febd090e97844c2d9197e71c98ce143888297e7c4b14aa7fef4cd555afb702cc6d75acc409f8bcfd340e6a6738fc429e25ff8c7a3737c9e2c26

test:
  secret_key_base: 2122c07e22716abe4ce8136b38f907c03adc6a4f6add84a39e636222665cdbfc551ee3e61e9b48a0ad628c8ce86657e2b2a1fafd198abfd1e99269116d8dd9f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
